from clinic.views.pages import (
    booking,
    booking_doctors,
    booking_services,
    contacts,
    direction_detail,
    directions_list,
    doctor_detail,
    doctors_list,
    handler404,
    handler500,
    home,
    price_list,
    privacy,
    service_detail,
    services_list,
    surgical_operations_list,
)

__all__ = [
    'home',
    'directions_list',
    'direction_detail',
    'doctors_list',
    'doctor_detail',
    'services_list',
    'service_detail',
    'price_list',
    'surgical_operations_list',
    'contacts',
    'privacy',
    'booking',
    'booking_services',
    'booking_doctors',
    'handler404',
    'handler500',
]
