# Generated by Django 6.0.6 on 2026-07-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, upload_to='directions/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Напрямок',
                'verbose_name_plural': 'Напрямки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TEN clinic', max_length=100, verbose_name='Назва сайту')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип')),
                ('about_text', models.TextField(blank=True, verbose_name='Про клініку (коротко)')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адреса')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Додатковий телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='URL карти (embed)')),
                ('directions_text', models.TextField(blank=True, verbose_name='Як доїхати')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для заявок')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')], unique=True, verbose_name='День тижня')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Відкриття')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закриття')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Вихідний')),
            ],
            options={
                'verbose_name': 'Графік роботи',
                'verbose_name_plural': 'Графік роботи',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткий опис')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (хв)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('price_note', models.CharField(blank=True, max_length=200, verbose_name='Примітка до ціни')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.direction', verbose_name='Напрямок')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='doctors/', verbose_name='Фото')),
                ('specialization', models.CharField(max_length=200, verbose_name='Спеціалізація')),
                ('bio', models.TextField(verbose_name='Біографія')),
                ('education', models.TextField(blank=True, verbose_name='Освіта')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж (років)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinic.direction', verbose_name='Напрямок')),
                ('services', models.ManyToManyField(blank=True, related_name='doctors', to='clinic.service', verbose_name='Послуги')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('preferred_date', models.DateField(verbose_name='Бажана дата')),
                ('preferred_time', models.CharField(blank=True, max_length=50, verbose_name='Бажаний час')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('confirmed', 'Підтверджена'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.direction', verbose_name='Напрямок')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.doctor', verbose_name='Лікар')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Заявка на запис',
                'verbose_name_plural': 'Заявки на запис',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('contacts', 'Контакти'), ('booking', 'Запис')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото')], default='text', max_length=16)),
                ('text_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
        migrations.CreateModel(
            name='Bookingsettings',
            fields=[
            ],
            options={
                'verbose_name': 'Запис — Повідомлення',
                'verbose_name_plural': 'Запис — Повідомлення',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homeaboutsettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Про клініку',
                'verbose_name_plural': 'Головна — Про клініку',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homectasettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — CTA',
                'verbose_name_plural': 'Головна — CTA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homeherosettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Sitefootersettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сайт — Footer',
                'verbose_name_plural': 'Сайт — Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
    ]
