# Generated by Django 6.0.6 on 2026-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='services_overview',
            field=models.TextField(blank=True, help_text='Один пункт на рядок.', verbose_name='Наші послуги'),
        ),
        migrations.AddField(
            model_name='direction',
            name='when_to_visit',
            field=models.TextField(blank=True, help_text='Один пункт на рядок.', verbose_name='Коли звернутися'),
        ),
    ]
