# Generated by Django 6.0.6 on 2026-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_direction_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Короткий опис'),
        ),
    ]
