# Generated by Django 6.0.6 on 2026-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_direction_short_description_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitefootersettings',
        ),
        migrations.CreateModel(
            name='Contactspagesettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка «Контакти»',
                'verbose_name_plural': 'Сторінка «Контакти»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Directiondetailsettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка напрямку (спільні тексти)',
                'verbose_name_plural': 'Сторінка напрямку (спільні тексти)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Directionspagesettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка «Напрямки»',
                'verbose_name_plural': 'Сторінка «Напрямки»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Doctorspagesettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка «Лікарі»',
                'verbose_name_plural': 'Сторінка «Лікарі»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homecontactssettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Контакти',
                'verbose_name_plural': 'Головна — Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homedirectionssettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Напрямки',
                'verbose_name_plural': 'Головна — Напрямки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Homedoctorssettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Лікарі',
                'verbose_name_plural': 'Головна — Лікарі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Privacysettings',
            fields=[
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Servicespagesettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка «Послуги та ціни»',
                'verbose_name_plural': 'Сторінка «Послуги та ціни»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Sitemenusettings',
            fields=[
            ],
            options={
                'verbose_name': 'Меню та шапка',
                'verbose_name_plural': 'Меню та шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.CreateModel(
            name='Surgicalsettings',
            fields=[
            ],
            options={
                'verbose_name': 'Хірургічні операції',
                'verbose_name_plural': 'Хірургічні операції',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='bookingsettings',
            options={'verbose_name': 'Сторінка «Запис»', 'verbose_name_plural': 'Сторінка «Запис»'},
        ),
        migrations.AlterModelOptions(
            name='homectasettings',
            options={'verbose_name': 'Головна — Запис (CTA)', 'verbose_name_plural': 'Головна — Запис (CTA)'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головна — Головний екран', 'verbose_name_plural': 'Головна — Головний екран'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='image',
            field=models.ImageField(blank=True, help_text='Мініатюра напрямку в каталозі та на головній. Рекомендований розмір: 480×576 px (5:6). Формат: JPG або PNG, оптимізований для веб.', upload_to='directions/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Портрет на картці лікаря та сторінці профілю. Рекомендований розмір: 360×408 px (15:17). Формат: JPG або PNG, оптимізований для веб.', upload_to='doctors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('directions', 'Напрямки'), ('doctors', 'Лікарі'), ('services', 'Послуги'), ('contacts', 'Контакти'), ('booking', 'Запис'), ('privacy', 'Конфіденційність'), ('surgical', 'Хірургія'), ('direction', 'Сторінка напрямку')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='Застаріле поле. Основний текст — у «Контент → Про клініку».', verbose_name='Про клініку (резерв)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Відображається у шапці та підвалі сайту. Рекомендований розмір: 613×410 px (≈3:2). Формат: JPG або PNG, оптимізований для веб.', upload_to='site/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Короткий рядок під логотипом у підвалі, наприклад «Medicine & Surgery».', max_length=200, verbose_name='Слоган під логотипом'),
        ),
    ]
