# Generated by Django 6.0.6 on 2026-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_cms_full_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Відображається на головній, сторінці «Контакти» та в підвалі.', max_length=500, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Основний номер для дзвінків на всьому сайті.', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Необовʼязковий другий номер на сторінці «Контакти».', max_length=20, verbose_name='Додатковий телефон'),
        ),
    ]
