# Generated by Django 6.0.6 on 2026-07-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_hearingaid_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearingaidssettings',
            fields=[
            ],
            options={
                'verbose_name': 'Слухові апарати',
                'verbose_name_plural': 'Слухові апарати',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.sitesettings',),
        ),
    ]
