# Generated by Django 6.0.6 on 2026-07-07 07:27

from django.db import migrations, models


def copy_direction_to_directions(apps, schema_editor):
    Doctor = apps.get_model('clinic', 'Doctor')
    for doctor in Doctor.objects.exclude(direction_id__isnull=True):
        doctor.directions.add(doctor.direction_id)


def restore_direction_from_directions(apps, schema_editor):
    Doctor = apps.get_model('clinic', 'Doctor')
    for doctor in Doctor.objects.all():
        direction = doctor.directions.order_by('order', 'name').first()
        if direction:
            doctor.direction_id = direction.pk
            doctor.save(update_fields=['direction_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_hearingaidssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='directions',
            field=models.ManyToManyField(
                related_name='doctors',
                to='clinic.direction',
                verbose_name='Напрямки',
            ),
        ),
        migrations.RunPython(copy_direction_to_directions, restore_direction_from_directions),
        migrations.RemoveField(
            model_name='doctor',
            name='direction',
        ),
    ]
