# Generated by Django 6.0.6 on 2026-07-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_doctor_directions_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('call', 'Дзвінок'), ('sms', 'SMS'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Спосіб звʼязку'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_direction_undecided',
            field=models.BooleanField(default=False, verbose_name='Напрямок не визначено'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.direction', verbose_name='Напрямок'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Бажана дата'),
        ),
    ]
