# Generated by Django 6.0.6 on 2026-07-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_homeaboutussettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
            ],
            options={
                'verbose_name': 'Послуга каталогу',
                'verbose_name_plural': 'Послуги каталогу',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.service',),
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
            ],
            options={
                'verbose_name': 'Позиція прайсу',
                'verbose_name_plural': 'Прайс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.service',),
        ),
    ]
