# Generated by Django 6.0.6 on 2026-07-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_about_us_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homeaboutussettings',
        ),
    ]
